modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="customvillagertrades"
version="1.16 v5"
displayName="Custom Villager Trades"
authors="SpaceCat97"
description='''
Allows you to add your own trades for villagers using several config files.
'''
